#data colections: KLA
collections:
  daytrip:
    output: true
    permalink: /daytrip/:path/
  private_safari:
    output: true
    permalink: /private-safari/:path/
  treks_and_activities:
    output: true
    permalink: /treks-and-other-activities/:path/

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
plugins_dir:
  # - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _pug
  - _sass
  - _js
  - package.json
  - package-lock.json
  - gulpfile.js
  - README.md