# global context
[build]
  publish = "_public/"
  command = "npm run gulptask && jekyll build"
# build a preview (optional)
[context.deploy-preview]
  command = "gulp build-preview"
# build a branch with debug (optional)
[context.branch-deploy]
  command = "gulp build-debug"