tel: "0788383215"
tel_display: "078 838 3215"

seo: 
  tagline: Safari Holidays That Inspire 

Memberships:
  logo:
    fields:
      alt: "Safari Bookings"
      file: "./img/uploads/bird-1"

