backend:
  name: github
  repo: i-meets-i/kibokoland-adventure-website-redesign

media_folder: "img/uploads/"

collections:
  - name: "website-settings"
    label: "Kibokoland Website Settings"
    files:
      - label: "Kibokoland Infomation"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"
          - label: "email"
            name: "email"
            widget: "string"
          - label: "Tel"
            name: "tel"
            widget: "string"
          - label: "email"
            name: "email"
            widget: "string"
