backend:
  name: github
  repo: i-meets-i/kibokoland-adventure-website-redesign

media_folder: "./img/uploads/"
public_folder: "uploads"

collections:
  - name: "website-settings"
    label: "Kibokoland Website Settings"
    files:
      - label: "Kibokoland's Data"
        name: "site_data"
        file: "_data/site_data.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"
          - label: "email"
            name: "email"
            widget: "string"
          - label: "Social Media Links"
            name: "social"
            widget: "object"
            fields:
              - label: "Facebook"
                name: "facebook"
                widget: "object"
                fields:
                  - label: "Account Link"
                    name: "url"
                    widget: "string"
                  - label: "User Name"
                    name: "user_name"
                    widget: "string"

              - label: "Instagram"
                name: "instagram"
                widget: "object"
                fields:
                  - label: "Account Link"
                    name: "url"
                    widget: "string"
                  - label: "User Name"
                    name: "user_name"
                    widget: "string"

              - label: "Twitter"
                name: "twitter"
                widget: "object"
                fields:
                  - label: "Account Link"
                    name: "url"
                    widget: "string"
                  - label: "User Name"
                    name: "user_name"
                    widget: "string"

              
              - label: "Trip Advisor"
                name: "trip_advisor"
                widget: "object"
                fields:
                  - label: "Account Link"
                    name: "url"
                    widget: "string"
                  - label: "User Name"
                    name: "user_name"
                    widget: "string"


  - name: "Pages"
    label: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "fold"
            name: "fold"
            widget: "object"
            fields:
              - label: "tagline"
                name: "tagline"
                widget: "string"
              - label: "Image"
                name: "background_image"
                widget: "image"
  - label: "Day Trips"
    name: "daytrips"
    folder: "_posts/daytrip"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hiden"
        default: "destination"

      - label: "Category"
        name: "category"
        widget: "hiden"
        default: "daytrips"

      - label: "Permalink"
        name: "permalink"
        widget: "hiden"
        default: "/:categories/:title/"

      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"

      - label: "Destination Data"
        name: "sys"
        widget: "object"
        fields:
          - label: "Icons"
            name: "icon"
            widget: "markdown"

          - label: "Circuit"
            name: "circuit"
            widget: "markdown"

          - label: "Fields"
            name: "fields"
            widget: "object"
            fields:
              - label: "Customer Review"
                name: "review"
                widget: "string"

              - label: "Price Per Person Per Day/Event"
                name: "price"
                widget: "string"

              - label: "Best Time To Visit"
                name: "best_time"
                widget: "markdown"

              - label: "Image"
                name: "image"
                widget: "object"
                fields:
                  - label: "Fields"
                    name: "fields"
                    widget: "object"
                    fields:
                     - label: "Image Desctiption"
                       name: "alt"
                       widget: "string"

                     - label: "File"
                       name: "file"
                       widget: "object"
                       fields:
                         - label: "Image Location"
                           name: "url" 
                           widget: "image"

      - label: "Image Slide"
        name: "image_corousel"
        alow-add: true
        widget: "list"
        field: {label: Image, name: image, widget: image} 

      - label: "Overview"
        name: "overview"
        widget: "object"
        fields:
          - label: "Inside Scoop"
            name: "intro"
            widget: "markdown"

          - label: "Tour Details"
            name: "tour_details"
            widget: "object"
            fields:
              - label: "When"
                name: "when"
                widget: "markdown"

              - label: "Duration"
                name: "duration"
                widget: "markdown"
                
              - label: "Language"
                name: "language"
                widget: "markdown"
                
              - label: "Included in price"
                name: "price_includes"
                widget: "markdown"
                
              - label: "Transport"
                name: "transport"
                widget: "markdown"

              - label: "Itinerary"
                name: "itinerary"
                widget: "markdown"

          - label: "Settings"
            name: "setting"
            widget: "object"
            fields:
              - label: "Activities"
                name: "activities"
                widget: "markdown"

              - label: "Hash Tags"
                name: "hashtags"
                widget: "markdown"

          - label: "Included"
            name: "included"
            widget: "list"
            alow-add: true
            field: {label: item, name: item, widget: string}

          - label: "Excluded"
            name: "excluded"
            widget: "list"
            alow-add: true
            field: {label: item, name: item, widget: markdown}

          - label: "Remarks"
            name: "remarks"
            widget: "list"
            alow-add: true
            field: {label: item, name: item, widget: markdown}
          
      - label: "What to Experience"
        name: "experience"
        widget: "object"
        field:
          - label: "what to see"
            name: "what_to_see"
            widget: "list" 
            alow-add: true
            field: {label: item, name: item, widget: markdown} 

      - label: "What to Expect"
        name: "expect"
        widget: "object"
        fields:
          - label: "Fields"
            name: "fields"
            widget: "object" 
            fields: 
              - label: "Video"
                name: "video"
                widget: "object"
                field: {label: File, name: url, widget: string} 

      - label: "Itinerary"
        name: "itinerary"
        widget: "list"
        alow-add: true
        field: {label: Video Embed Link, name: url, widget: markdown} 

      - label: "Remarks"
        name: "remarks"
        widget: "list"
        alow-add: true
        field: {label: Remark, name: remark, widget: markdown} 
                  