backend:
  name: github
  repo: i-meets-i/kibokoland-adventure-website-redesign

media_folder: "/img/uploads/"

collections:
  - name: "website-settings"
    label: "Kibokoland Website Settings"
    files:
      - label: "Kibokoland's Data"
        name: "site_data"
        file: "_data/site_data.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"
          - label: "email"
            name: "email"
            widget: "string"
          #social media data
          - label: "Social Media Links"
            name: "social"
            widget: "object"
            fields:
              
              # facebook
              - label: "Facebook"
                name: "facebook"
                fields:
                  - label: "Account Link"
                    name: "url"
                    widget: "string"
                  - label: "User Name"
                    name: "user_name"
                    widget: "string"

              # insta gram
              - label: "Instagram"
                name: "instagram"
                fields:
                  - label: "Account Link"
                    name: "url"
                    widget: "string"
                  - label: "User Name"
                    name: "user_name"
                    widget: "string"
              #twitter
              - label: "Twitter"
                name: "twitter"
                fields:
                  - label: "Account Link"
                    name: "url"
                    widget: "string"
                  - label: "User Name"
                    name: "user_name"
                    widget: "string"
              #end twitter
              
              - label: "Trip Advisor"
                name: "trip_advisor"
                fields:
                  - label: "Account Link"
                    name: "url"
                    widget: "string"
                  - label: "User Name"
                    name: "user_name"
                    widget: "string"


  - name: "Pages"
    label: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "fold"
            name: "fold"
            widget: "object"
            fields:
              - label: "tagline"
                name: "tagline"
                widget: "string"


